definitions:
  main.Image:
    properties:
      imageNameTag:
        type: string
    required:
    - imageNameTag
    type: object
info:
  contact: {}
  license: {}
paths:
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      operationId: get-string-by-int
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/main.Image'
      summary: Show a account
swagger: "2.0"
